### ISSUE TITLE
overlapped objects problem

### ISSUE THREAD

**Issue by sanhai77** [maxw1489/Mask_RCNN#1]
hi
i have problem in mask branch. in the paper mentioned:
The mask branch has a Km^2- dimensional output for each RoI, which encodes K binary masks of resolution m × m, one for each of the K classes.
but what if we have two overlapped object with same class in one roi?
roi is made of main object + particle of other object(with same class of main object). how mask r-cnn distinct two object for instance segmentation for this roi?
for example in bellow image each rois involve several balloon.
![1_I5_PSpXNmPDp5K9zvUZLpg](https://github.com/maxw1489/Mask_RCNN/assets/141138029/29815945-9526-43ab-ba52-6c3fe08ab914)

**Comment by maxw1489** [comment]
That is the beauty of the DNN. The network learns to distinguish which object belongs to a specific ROI and trains to generate the respective mask. However, that doesn't mean you won't have some overlapped pixels for certain areas.
